# Basic OS Config
CONFIG_NEWLIB_LIBC=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=256000

# FPU Support (Crucial for math.pi)
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_DHCPV4=y

# USB & Shell
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="STM32 Lua Node"
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_UART_CONSOLE=y

# Increase Shell Stack for Lua
CONFIG_SHELL_STACK_SIZE=4096

# File System
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL=y

# Force LittleFS to respect the STM32H7 32-byte flash alignment
CONFIG_FS_LITTLEFS_READ_SIZE=32
CONFIG_FS_LITTLEFS_PROG_SIZE=32
CONFIG_FS_LITTLEFS_CACHE_SIZE=128
CONFIG_FS_LITTLEFS_LOOKAHEAD_SIZE=32

# Debugging Faults
CONFIG_HW_STACK_PROTECTION=y

CONFIG_NET_SHELL=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_STATISTICS=y
CONFIG_HTTP_SERVER=y
CONFIG_NET_GPTP=y
CONFIG_DNS_RESOLVER=y
CONFIG_NET_DHCPV4_LOG_LEVEL_INF=y
